version: '3.8'

services:
  auth_service:
    build: ./auth_service
    ports:
      - "8001:8000"
    networks:
      - backend

  game_catalog_service:
    build: ./game_catalog_service
    ports:
      - "8000:8000"
    depends_on:
      - auth_service
    networks:
      - backend

networks:
  backend: